version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "/app/app.sh", "[CI]"]
    env_file:
      - .env
    volumes:
      - ./download:/app/download